version: "3.9"

services:
  database:
    container_name: newzonesoflife-db
    mem_limit: 2048m
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network

  phpmyadmin:
    container_name: newzonesoflife-phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network

  wordpress:
    container_name: newzonesoflife-wp
    depends_on:
      - database
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      MANDRILL_API_KEY: '${MANDRILL_API_KEY:-md-uSYDOfF4dGAocY7s6UUrNg}'
      MANDRILL_USERNAME: '${MANDRILL_USERNAME:-31645118}'
      WORDPRESS_CONFIG_EXTRA: |
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $$_SERVER['HTTPS'] = 'on';
        }
        if (!defined('MANDRILL_API_KEY') && getenv('MANDRILL_API_KEY')) {
            define('MANDRILL_API_KEY', getenv('MANDRILL_API_KEY'));
        }
        if (!defined('MANDRILL_USERNAME') && getenv('MANDRILL_USERNAME')) {
            define('MANDRILL_USERNAME', getenv('MANDRILL_USERNAME'));
        }
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress-network
      - proxy-network

volumes:
  db-data:

networks:
  wordpress-network:
    driver: bridge
  proxy-network:
    name: nathalielesbachescom_default
    external: true

